project:
  type: website
  output-dir: docs
  resources: 
    - images/

website:
  title: "SDSLab"
  description: "SDS Lab of the Department of Geography Education, Seoul National University"
  favicon: images/seoul.png
  
  navbar:
    background: "#2A534D"
    foreground: "#ffffff"
    title: "Spatial Data Science Lab"
    logo: images/logo2.png
    search: true
    right:
      - text: "Members"
        file: members.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Publications & Presentations"
        file: publications.qmd
      - text: "News"
        file: news/index.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



